### ISSUE TITLE
progaurd rules

### ISSUE THREAD

**Issue by ghost** [ndori/RxLoading#1]
what about the progaurd rules??

**Comment by ndori** [comment]
Hi,
Thank you for your interest in the project. 

have you had any issues with Proguard?

This library uses RxJava and so the only Proguard rules I had to used are the ones belong to it.
you can find a project designed specifically for it on [RxJavaProGuardRules](https://github.com/artem-zinnatullin/RxJavaProGuardRules)

However, The library already use it so I don't think it is neccesary to add it on your own.
